// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbJ3u774YnfAPESNnXaXuzAN_JocaGm18',
    appId: '1:833167633397:web:e10e3072af60ec7db3cebc',
    messagingSenderId: '833167633397',
    projectId: 'evocative-nexus-398113',
    authDomain: 'evocative-nexus-398113.firebaseapp.com',
    storageBucket: 'evocative-nexus-398113.appspot.com',
    measurementId: 'G-EEHRZVYSZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxuDKHBFWXg9nQDmh3noRQM6jrRC7oBw',
    appId: '1:833167633397:android:38f4c40535cf775db3cebc',
    messagingSenderId: '833167633397',
    projectId: 'evocative-nexus-398113',
    storageBucket: 'evocative-nexus-398113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEihWroouPWmFTTH-vQo4WfJfCtujqv-I',
    appId: '1:833167633397:ios:a6af746ed6d8d39cb3cebc',
    messagingSenderId: '833167633397',
    projectId: 'evocative-nexus-398113',
    storageBucket: 'evocative-nexus-398113.appspot.com',
    androidClientId: '833167633397-fstfn0iq2pq0vfe4mouuosjfl4nfu19r.apps.googleusercontent.com',
    iosClientId: '833167633397-84cd0fde2mnrat0lhbl3eh2oma8dmtq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
